repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.3
    hooks:
      - id: clang-format
        name: clang-format (C++ only)
        files: \.(h|hpp|cpp)$
        types_or: [c, c++]
        additional_dependencies: []
